name: Maj-Soul News

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    - name: Fetch latest news
      id: fetch  # 给这个步骤一个ID
      run: |
        python maj_soul_news.py
        echo "::set-output name=news::$(cat news.txt)"  # 将news.txt的内容设置为输出变量
      
    - name: Send Feishu notification
      if: steps.fetch.outputs.news != ''  # 使用上一步的输出变量
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"'"${{ steps.fetch.outputs.news }}"'"}}' ${{ secrets.FEISHU_WEBHOOK }}

    - name: Commit files
      run: |
        git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --local user.name "${{ secrets.GIT_USER_NAME }}"
        git add last_news.txt news.txt
        git commit -m "Update news files" || echo "No changes to commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
