name: Monitor Website

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run monitoring script
      run: python monitor.py
      env:
        FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
